### ISSUE TITLE
cannot execute code with the "Run" menu

### ISSUE THREAD

**Issue by aligator** [GravityScore/LuaIDE#44]
If I try to run a simple program with the Run-menu, the program executes, but after pressing a key to return to luaide, it crashes:

parallel:22: luaide:924: Expected string

my program is only one print("hello") 
so it shouldn't be a problem with my program

**Comment by GravityScore** [comment]
Run program being removed in 2.0.

**Comment by GravityScore** [comment]
Actually on second thoughts I might keep it. Anyway, irrelevant for the new version...
