### ISSUE TITLE
Crash when changing themes

### ISSUE THREAD

**Issue by makromoo** [GravityScore/LuaIDE#53]
luaIDE:275 attempt to index ? (a nil value)

Using luaIDE 1.1

Changing a theme causes a crash, says Downloading... downloads and crashes.

**Comment by 1lann** [comment]
LuaIDE is undergoing a re-write, I believe the files are out of place so the current (old) version won't work correctly with themes. However, this will be resolved once the new version of LuaIDE is released.

**Comment by makromoo** [comment]
Ah can't wait till then! :+1:
