### ISSUE TITLE
2.0 Update breaks app

### ISSUE THREAD

**Issue by djfj74** [GravityScore/LuaIDE#54]

**Comment by djfj74** [comment]
@GravityScore FIX THIS, COME BACK TO THIS BELOVED PROJECT PLZ!

**Comment by djfj74** [comment]
@GravityScore

**Comment by djfj74** [comment]
@GravityScore

**Comment by nevercast** [comment]
@djfj74 

With all due respect. These projects are developed in our own spare time. We have no obligation to do any coding for you. We have lives, we have jobs and family and friends, we don't live and breathe to update things for you.

Issue a bug or fix request and a developer may or may not get time to see to it and fix it. We are not employed by our users to develop things for them, we are not just code monkeys that convert coffee to code for you.

So your options are:
- Wait patiently and _quietly_ for an update.
- Learn Lua and update it yourself.

These are the only two options.

We developers love seeing enthusiastic users enjoying our projects. But do not demand and pester us to fix things for you, we may not have the time.

**Comment by 1lann** [comment]
@djfj74 By the way, you can fix it yourself to revert it to the older version by forking it, changing the URLs in LuaIDE, then reverting the forked git repo to commit a66b127e4c04fe77a3345c8247294b6fe6752f36

**Comment by benanders** [comment]
Thank you. That expresses my opinion way more respectfully than in what I was planning to write. 

I'm busy at the moment and have no motivation to do anything with this right now. That might change in the future, but for now, Nevercast's options are the only ones you have.
